# fly.toml app configuration file generated for curriculum on 2025-11-20T19:03:07Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'curriculum'
primary_region = 'iad'

[build]

# Set environment variables for the application
[env]
  # Replace the URL with your actual Vercel frontend URL.
  # You can add multiple URLs separated by a comma.
  CORS_ALLOWED_ORIGINS = "https://curriculum-steel.vercel.app/,http://localhost:5173"
  CURRICULUM_DATA_URL = "https://trustdash.replit.app/api/configurations"
  LLM_MODEL = "gpt-4o"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
